export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const GET_COUNTRIES_TO_SELECT = "GET_COUNTRIES_TO_SELECT";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
